pluginManagement {
	repositories {
		gradlePluginPortal()
	}
}

plugins {
	id 'io.spring.develocity.conventions' version '0.0.27' apply false
	id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = 'tracing'

dependencyResolutionManagement.versionCatalogs {
	libs {
		if (providers.gradleProperty('INTERNAL_SNAPSHOT').map { it.toBoolean() }.getOrElse(false)) {
			String oldVersion = (file('gradle/libs.versions.toml').text =~ /(?m)^micrometer\s*=\s*["']([^"']+)["']/)[0][1]
			String newVersion = oldVersion.replaceFirst(/-(SNAPSHOT|M\d+|RC\d+)$/, '') + '-INTERNAL-SNAPSHOT'
			logger.warn("Using Micrometer INTERNAL-SNAPSHOT: $newVersion (instead of $oldVersion)")
			version('micrometer', newVersion)
		}
	}
}

// The develocity-conventions plugin reads spring.build-type from gradle.properties directly
// so it cannot be overridden with cli parameters or env vars.
if (providers.environmentVariable('SPRING_BUILD_TYPE').getOrElse('oss') == 'oss') {
	apply plugin: 'io.spring.develocity.conventions'
}
else {
	apply plugin: 'com.gradle.develocity'
	develocity.buildScan.publishing.onlyIf { false }
}

include 'micrometer-tracing', 'micrometer-tracing-bom', 'benchmarks'

['brave', 'otel'].each { bridge ->
	include "micrometer-tracing-bridge-$bridge"
	project(":micrometer-tracing-bridge-$bridge").projectDir = new File(rootProject.projectDir, "micrometer-tracing-bridges/micrometer-tracing-bridge-$bridge")
}

['test', 'integration-test'].each { testProject ->
	include "micrometer-tracing-$testProject"
	project(":micrometer-tracing-$testProject").projectDir = new File(rootProject.projectDir, "micrometer-tracing-tests/micrometer-tracing-$testProject")
}

['integration-test-spring-aop-with-aspectj', 'integration-test-spring-aop-no-aspectj', 'integration-test-jpms'].each { testProject ->
	include "micrometer-tracing-$testProject"
	project(":micrometer-tracing-$testProject").projectDir = new File(rootProject.projectDir, "internal/micrometer-tracing-$testProject")
}

include 'docs'
