:noheader:
[[tracing-documentation]]
= Tracing support

[[tracing-purpose]]
== Purpose

https://github.com/micrometer-metrics/tracing[Micrometer Tracing] provides a simple facade for the most popular tracer libraries, letting you instrument your JVM-based application code without vendor lock-in.
It is designed to add little to no overhead to your tracing collection activity while maximizing the portability of your tracing effort.

It also provides a tracing extension to Micrometer's `ObservationHandler` (from Micrometer 1.10.0).
Whenever an `Observation` is used, a corresponding span will be created, started, stopped and reported.

[[tracing-installing]]
== Installing

Micrometer Tracing comes with a Bill of Materials (BOM) which is a project that contains all the project versions for you.

The following example shows the required dependency in Gradle:

[source,groovy,subs=+attributes]
----
implementation platform('io.micrometer:micrometer-tracing-bom:latest.release')
implementation 'io.micrometer:micrometer-tracing'
----

The following example shows the required dependency in Maven:

[source,xml,subs=+attributes]
----
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-tracing-bom</artifactId>
            <version>${micrometer-tracing.version}</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>

<dependencies>
    <dependency>
      <groupId>io.micrometer</groupId>
      <artifactId>micrometer-tracing</artifactId>
    </dependency>
</dependencies>
----

You should add a tracing bridge you want to use, such as `micrometer-tracing-bridge-brave` or `micrometer-tracing-bridge-otel` and span exporters / reporters.
In case of adding a bridge the `micrometer-tracing` library is added transitively.
