= Supported Reporters

Micrometer Tracing supports directly the following Reporters.

* https://zipkin.io[*OpenZipkin Zipkin*]

== Installing

The following example shows the required dependency in Gradle (assuming that Micrometer Tracing BOM has been added):

.OpenZipkin Zipkin with Brave
[source,groovy,subs=+attributes]
----
implementation 'io.zipkin.reporter2:zipkin-reporter-brave'
----

.OpenZipkin Zipkin with OpenTelemetry
[source,groovy,subs=+attributes]
----
implementation 'io.opentelemetry:opentelemetry-exporter-zipkin'
----

CAUTION: Support for the OTel Zipkin Exporter has been deprecated because `opentelemetry-exporter-zipkin` was discontinued by OpenTelemetry.

.An OpenZipkin URL sender dependency to send out spans to Zipkin via a `URLConnectionSender`
[source,groovy,subs=+attributes]
----
implementation 'io.zipkin.reporter2:zipkin-sender-urlconnection'
----

The following example shows the required dependency in Maven (assuming that Micrometer Tracing BOM has been added):

.OpenZipkin Zipkin with Brave
[source,xml,subs=+attributes]
----
<dependency>
    <groupId>io.zipkin.reporter2</groupId>
    <artifactId>zipkin-reporter-brave</artifactId>
</dependency>
----

.OpenZipkin Zipkin with OpenTelemetry
[source,xml,subs=+attributes]
----
<dependency>
    <groupId>io.opentelemetry</groupId>
    <artifactId>opentelemetry-exporter-zipkin</artifactId>
</dependency>
----

CAUTION: Support for the OTel Zipkin Exporter has been deprecated because `opentelemetry-exporter-zipkin` was discontinued by OpenTelemetry.

.An OpenZipkin URL sender dependency to send out spans to Zipkin via a `URLConnectionSender`
[source,xml,subs=+attributes]
----
<dependency>
    <groupId>io.zipkin.reporter2</groupId>
    <artifactId>zipkin-sender-urlconnection</artifactId>
</dependency>
----

