dependencies {
    jmh project(':micrometer-tracing-bridge-brave')
    jmh project(':micrometer-tracing-bridge-otel')
    jmh libs.jmh
    jmh 'io.zipkin.brave:brave-tests'

    jmh libs.logback

    // Nebula doesn't like having jmhAnnotationProcessor without jmh so we just add it twice.
    jmh libs.jmhGeneratorAnnProcess
    jmhAnnotationProcessor libs.jmhGeneratorAnnProcess
}

jmh {
    jmhVersion = '1.37'
    fork = 2
    warmupIterations = 3
    iterations = 5
    duplicateClassesStrategy = DuplicatesStrategy.EXCLUDE
    zip64 = true
    if (project.hasProperty('jmhInclude')) {
        includes = [project.property('jmhInclude')]
    }
    profilers = ['gc']
}
