name: Merge Dependabot PR

on:
  pull_request:
    branches:
      - main
      - '*.x'

run-name: Merge Dependabot PR ${{ github.ref_name }}

jobs:
  merge-dependabot-pr:
    permissions: write-all

    # Until v6 is released
    uses: spring-io/spring-github-workflows/.github/workflows/spring-merge-dependabot-pr.yml@7f3e83751a6188de5c701b6d79b4394d5cbd1498
    with:
      autoMerge: true
      mergeArguments: --auto --squash
