name: Post Release Tasks

on:
  workflow_dispatch:
    inputs:
      github_ref_name:
        description: "Current release tag in this train (e.g., v1.15.3)"
        required: true
      previous_ref_name:
        description: "Previous release tag in this train (e.g., v1.14.8)"
        required: false

jobs:
  post_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Post Release Tasks
        uses: marcingrzejszczak/micrometer-release@v0.0.1
        with:
          gh_token: ${{ secrets.GH_ACTIONS_REPO_TOKEN }}
          github_ref_name: ${{ github.event.inputs.github_ref_name }}
          previous_ref_name: ${{ github.event.inputs.previous_ref_name }}
          spring_release_gchat_webhook_url: ${{ secrets.SPRING_RELEASE_GCHAT_WEBHOOK_URL }}
          bluesky_handle: ${{ secrets.BLUESKY_HANDLE }}
          bluesky_password: ${{ secrets.BLUESKY_PASSWORD }}
